# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-09 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='加入时间')),
                ('name', models.CharField(default='none', max_length=50, verbose_name='频道名称')),
                ('freq', models.FloatField(verbose_name='频点')),
                ('district', models.IntegerField(default=1, verbose_name='所属区域')),
                ('type', models.IntegerField(default=1, verbose_name='种类')),
            ],
            options={
                'verbose_name': '白名单',
                'db_table': 'tb_whitelist',
            },
        ),
        # migrations.CreateModel(
        #     name='WhiteListCategory',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(default='普通', max_length=50, verbose_name='类型名称')),
        #         ('islegal', models.CharField(default='1', max_length=50, verbose_name='是否合法')),
        #     ],
        #     options={
        #         'verbose_name': '白名单类型',
        #         'db_table': 'tb_whcategory',
        #     },
        # ),
    ]
