# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='普通', max_length=50, verbose_name='类型名称')),
                ('islegal', models.CharField(default='1', max_length=50, verbose_name='是否合法')),
            ],
            options={
                'db_table': 'tb_whcategory',
                'verbose_name': '白名单类型',
            },
        ),
    ]
