# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-09 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteList', '0002_whitelistcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 15, 25, 6, 774133), verbose_name='加入时间'),
        ),
    ]
