# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con_control', '0002_auto_20201014_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuserecord',
            name='version',
            field=models.CharField(default='1.0.0', max_length=50, verbose_name='打卡时的版本'),
        ),
    ]
