# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-20 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('con_control', '0020_auto_20210720_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 7, 20, 11, 22, 57, 855772), verbose_name='加入时间')),
                ('name', models.CharField(max_length=50, verbose_name='种类名称')),
                ('num', models.CharField(default='0', max_length=50, verbose_name='编码')),
            ],
            options={
                'verbose_name': '黑广播种类',
                'db_table': 'tb_BlackCategory',
            },
        ),
        migrations.CreateModel(
            name='BlackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='上传时间')),
                ('lnglat', models.CharField(max_length=50, verbose_name='上传坐标')),
                ('address', models.CharField(default='null', max_length=100, verbose_name='坐标具体可读地址')),
                ('datafrom', models.CharField(default='baidu', max_length=50, verbose_name='可读地址数据来源')),
                ('district', models.IntegerField(default=1, verbose_name='所属区域')),
                ('freq', models.FloatField(verbose_name='频率')),
                ('name', models.CharField(default='0', max_length=50, verbose_name='频点名称')),
                ('record', models.CharField(default='0', max_length=100, verbose_name='录音名称')),
                ('recordtime', models.CharField(default='0s', max_length=50, verbose_name='录音时长')),
                ('acquisitionmode', models.CharField(default='0', max_length=50, verbose_name='采集模式')),
                ('confidencelevel', models.CharField(default='0', max_length=50, verbose_name='黑广播置信度')),
                ('islegal', models.CharField(default='0', max_length=50, verbose_name='是否合法')),
                ('contact', models.CharField(default='无', max_length=50, verbose_name='联系方式')),
                ('common', models.CharField(default='无', max_length=300, verbose_name='备注')),
                ('monitor', models.CharField(default='', max_length=200, verbose_name='上报人姓名')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='con_brocast.BlackCategory', verbose_name='种类')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='con_control.MobileInfo', verbose_name='上传手机系统id')),
            ],
            options={
                'verbose_name': '黑广播记录',
                'db_table': 'tb_Broadcasting',
            },
        ),
    ]
