# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-20 11:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con_brocast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcategory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 11, 23, 57, 347270), verbose_name='加入时间'),
        ),
    ]
