# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con_brocast', '0003_auto_20210621_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcategory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 14, 22, 49, 589387), verbose_name='加入时间'),
        ),
    ]
