# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con_brocast', '0005_auto_20210624_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcategory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 14, 23, 55, 326066), verbose_name='加入时间'),
        ),
    ]
