# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con_brocast', '0008_auto_20210624_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcategory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 14, 32, 21, 64633), verbose_name='加入时间'),
        ),
    ]
