# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-11 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileToPlatformInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, verbose_name='手机id')),
                ('platform', models.IntegerField(default=0, verbose_name='平台')),
            ],
            options={
                'db_table': 'tb_MobileToPlatform',
                'verbose_name': '手机对应平台',
            },
        ),
        migrations.CreateModel(
            name='PlatformInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='平台版本')),
                ('district', models.CharField(max_length=50, verbose_name='平台所属地区')),
                ('app', models.CharField(max_length=50, verbose_name='app版本号')),
            ],
            options={
                'db_table': 'tb_Platform',
                'verbose_name': '平台信息',
            },
        ),
    ]
