# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-16 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletoplatforminfo',
            name='name',
            field=models.CharField(default='none', max_length=50, verbose_name='手机名'),
        ),
    ]
