# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-21 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20210309_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileversion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 14, 29, 51, 325388), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='rediotest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 14, 29, 51, 325388), verbose_name='收测时间'),
        ),
    ]
