# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_auto_20210624_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileversion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 14, 28, 48, 594096), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='rediotest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 14, 28, 48, 594096), verbose_name='收测时间'),
        ),
    ]
